name: "Test and Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v10
        with:
          name: pete1232
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check
      - run: nix build --json
